databases:
  - name: mobilite-db
    plan: free
    databaseName: mobilite_durable
    user: mobilite

services:
  - type: web
    name: mobilite-dashboard
    plan: free
    region: frankfurt
    runtime: docker
    dockerfilePath: ./Dockerfile.render
    envVars:
      - key: PORT
        value: "10000"
      - key: DATABASE_URL
        fromDatabase:
          name: mobilite-db
          property: connectionString
      - key: ENV
        value: production
      - key: PYTHONPATH
        value: .
      - key: TOMTOM_API_KEY
        sync: false
      - key: POWERBI_PUSH_URL_LILLE
        sync: false
      - key: POWERBI_PUSH_URL_MONTPELLIER
        sync: false
